### ISSUE TITLE
'module' object has no attribute 'byte'

### ISSUE THREAD

**Issue by 3DTOPO** [s9xie/hed#76]
I installed and compiled hed at: /home/jeshua/hed

I set:
export CAFFE_ROOT=/home/jeshua/hed
export PYTHONPATH=/home/jeshua/hed/distribute:/home/jeshua/hed/distribute/python:/home/jeshua/hed/python/caffe:$PYTHONPATH

But when I attempt to import caffe I get the error _'module' object has no attribute 'byte'_

\> python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import caffe

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeshua/hed/distribute/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/jeshua/hed/distribute/python/caffe/pycaffe.py", line 11, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 74, in <module>
    from numpy.testing import _numpy_tester
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 6, in <module>
    from .nose_tools.decorators import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/nose_tools/decorators.py", line 20, in <module>
    from .utils import SkipTest, assert_warns
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/nose_tools/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/usr/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/home/jeshua/hed/python/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/home/jeshua/.local/lib/python2.7/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/home/jeshua/.local/lib/python2.7/site-packages/skimage/util/__init__.py", line 1, in <module>
    from .dtype import (img_as_float32, img_as_float64, img_as_float,
  File "/home/jeshua/.local/lib/python2.7/site-packages/skimage/util/dtype.py", line 19, in <module>
    _integer_types = (np.byte, np.ubyte,          # 8 bits
AttributeError: 'module' object has no attribute 'byte'`

**Comment by 3DTOPO** [comment]
This error goes away if I remove a previous caffe directory from the PYTHONPATH environment variable.
