### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__caffe)

### ISSUE THREAD

**Issue by 3DTOPO** [s9xie/hed#77]
I installed and compiled hed at: /home/jeshua/hed

I set:
`export CAFFE_ROOT=/home/jeshua/hed/build/install/`
`export PYTHONPATH=/home/jeshua/hed/build/install/python`

But when I attempt to import caffe I get the error:
`ImportError: dynamic module does not define module export function (PyInit__caffe)`

`> python`
`Python 3.5.2 (default, Nov 12 2018, 13:43:14) `
`[GCC 5.4.0 20160609] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import caffe`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/home/jeshua/hed/build/install/python/caffe/__init__.py", line 1, in <module>`
`    from .pycaffe import Net, SGDSolver`
`  File "/home/jeshua/hed/build/install/python/caffe/pycaffe.py", line 13, in <module>`
`    from ._caffe import Net, SGDSolver`
`ImportError: dynamic module does not define module export function (PyInit__caffe)`

**Comment by 3DTOPO** [comment]
Ooops - it was compiled for python 2.7, but was using Python 3.5 above.
